### PR TITLE
better support for airgap mode 'exists', secure rke2 token by default, allow setting rke2_node_name, implement local artifact download and push to remote fallback

### PR DESCRIPTION
**Pull request by simonfelding**
# Description

There's a bunch of stuff in this commit. I realize it could have been multiple pull requests. Sorry about that. 

- added better support for airgap mode 'exists' in rke2.yml
- deprecate rke2_snapshooter spelling error
- secure rke2 token by default
- fix indent of registries config (broke with tls_no_verify set)
- allow setting rke2_node_name as node name
- split logical `and` to multiple lines for readability
- made the role guess if server or agent based on group it belongs to
- implement local artifact download and push to remote fallback
- updated documentation to match

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Small minor change not affecting the Ansible Role code (GitHub Actions Workflow, Documentation etc.)

## How Has This Been Tested?
reset my local cluster entirely and ran each feature against it.

### CODE REVIEW

**Comment by MonolithProjects** [comment]
Hi @simonfelding, please resolve the conflicts

**Comment by simonfelding** [comment]
@MonolithProjects I fixed the conflicts, is it okay now?

**Comment by Duke1715** [comment]
@MonolithProjects Hi! When can we expect the merge? I found some interesting changes there for use that I would like to see in the master.

**Comment by simonfelding** [comment]
> @MonolithProjects Hi! When can we expect the merge? I found some interesting changes there for use that I would like to see in the master.

Maybe I should split it into multiple PRs, it got kind of large..

**Comment by MonolithProjects** [comment]
> > @MonolithProjects Hi! When can we expect the merge? I found some interesting changes there for use that I would like to see in the master.
> 
> Maybe I should split it into multiple PRs, it got kind of large.. 

Yeah... I think that's a good idea. Plus I see in this PR commits which are already in Master and this makes it harder to review. Please split it and I am sure I can find a time to check it 😉 Thanks!

**Comment by simonfelding** [comment]
I split it up into several new pull requests. some of the changes have already been implemented by other people.

**Pull request closed without merging**
