### PR TITLE
feat: Added option to customize kubelet arguments

### PR DESCRIPTION
**Pull request by lukapetrovic-git**
# Description

Added option to customize kubelet arguments [(https://docs.rke2.io/reference/server_config#agentflags)](https://docs.rke2.io/reference/server_config#agentflags). 

I used the variable _rke2_server_options_ somewhat successfully too, but it becomes very messy very fast since it requires specifying all kubelet arguments on a single line like so:

```
rke2_server_options:
  - "kubelet-arg: ['--system-reserved=cpu=100m,memory=100Mi,pid=100000','--kube-reserved=cpu=80m,memory=1400Mi,pid=100000','--eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<15%','--enforce-node-allocatable=pods', '--pod-max-pids=32768']"
```

I would constantly break it trying to add new/adjust existing arguments so i created a new variable so that arguments can be passed like below:

```
rke_kubelet_arg:
  - "--system-reserved=cpu=100m,memory=100Mi,pid=100000"
  - "--kube-reserved=cpu=80m,memory=1400Mi,pid=100000"
  - "--eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<15%"
  - "--enforce-node-allocatable=pods"
  - "--pod-max-pids=32768"
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Small minor change not affecting the Ansible Role code (Github Actions Workflow, Documentation, etc.)

## How Has This Been Tested?
I have been successfully using this variable on all my environments both dev/test and production in the last month or so.

### CODE REVIEW

**Review by MonolithProjects — APPROVED** [review]
LGTM. Thanks

**Comment by lukapetrovic-git** [comment]
@MonolithProjects I just noticed i named the variable rke_kubelet_arg instead of rke**2**_kubelet_arg and pushed another commit just to stay consistent across all vars.

**Review by MonolithProjects — APPROVED** [review]
LGTM

**Comment by MonolithProjects** [comment]
> @MonolithProjects I just noticed i named the variable rke_kubelet_arg instead of rke**2**_kubelet_arg and pushed another commit just to stay consistent across all vars. 

Thanks. I didn't notice that too.

**Comment by albundy83** [comment]
Hello,
just to harmonize things, won't it be possible to use the same format than `kube_controller_manager` and `kube_scheduler_arg`:

```yaml
# rke2_kube_controller_manager_arg:
#   - "bind-address=0.0.0.0"

# rke2_kube_scheduler_arg:
#   - "bind-address=0.0.0.0"
```

Like this (I have removed `--` from parameter)
```yaml
# (Optional) Customize default kubelet arguments
# rke2_kubelet_arg:
#   - "system-reserved=cpu=100m,memory=100Mi"
```

instead of:
```yaml
# (Optional) Customize default kubelet arguments
# rke2_kubelet_arg:
#   - "--system-reserved=cpu=100m,memory=100Mi"
```

**Pull request merged**
