### PR TITLE
 Adding support for Kube-vip as HA VIP provider 

### PR DESCRIPTION
**Pull request by ProjectInitiative**
# Description

Adding support for additional HA option, kube-vip within cluster

## Type of change

- added kube-vip templates
- updated defaults and README for kube-vip
- new additions do not interfere with default environment
- cleaned up some ansible linting errors

## How Has This Been Tested?
Provisioned a cluster on Proxmox as well as several with Vagrant locally.

### CODE REVIEW

**Comment by ProjectInitiative** [comment]
I would like to add that there are several more options to add as potential variables (like upnp support and such) see `templates/kube-vip/kubevip.yml.js` for most of the included variables

**Comment by MonolithProjects** [comment]
Hi @ProjectInitiative , yeah i noticed that. I think we can go with your current solution (additional variables can be added in future iterations). So, i am fine with merging this PR (once you will fix that file permissions) 😉

**Comment by ProjectInitiative** [comment]
I will try to change the template permissions to match the others in the repo. Strange it didn't trip on the other kube-vip templates as they all have the same permissions.

**Comment by MonolithProjects** [comment]
@ProjectInitiative you need to add the permissions settings directly to the template task. Something like this:

```
...
    owner: root
    group: root
    mode: 0644
...
```

**Review by MonolithProjects — APPROVED** [review]
lgtm

**Pull request merged**
